### ISSUE TITLE
1st and 2nd steps are wrong in the mentioned doc

### ISSUE THREAD

**Issue by jagadeeshbabuchinde** [NetAppDocs/sc-plugin-vmware-vsphere#16]
Page: [Migrate from Windows-based SnapCenter Plug-in for VMware vSphere](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_migrate_from_windows_based_snapcenter_plug-in_for_vmware_vsphere.html)

In 1st step we are giving wrong info, as we are talking about upgrading the snapcenter and the extension should be **.exe** but we are referring as ISO. 

In 2nd step we need to make sure that no backups should be running on SCV and no need to disable the existing SCV plugin.

Please correct these two steps

**Comment by netapp-madhulik** [comment]
Thank you for reporting this. The steps are updated.
