### ISSUE TITLE
Topic: Attach VMDKs to a VM is redirecting to "404 error" page

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/sc-plugin-vmware-vsphere#19]
Page: [Overview](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_restore_from_backups_overview.html)

From: Takahashi, Hideyuki <Hideyuki.Takahashi@netapp.com> 
Sent: Tuesday, July 20, 2021 2:20 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_restore_from_backups_overview.html

Hi Team,

"Attach VMDKs to a VM" seems to be broken link.

Restore from backups
-> Attach VMDKs to a VM
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_attach_vmdks_to_a_vm.html

Regards,
Hideyuki Takahashi

**Comment by netapp-madhulik** [comment]
Thank you for reporting this. The broken link is now fixed.

Regards,
Madhulika
