### ISSUE TITLE
SCV 4.4 - Upgrade Workflow Diagram Needs Updating

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/sc-plugin-vmware-vsphere#2]
Page: [Deployment workflow for existing users](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_workflow_for_existing_users.html)

The upgrade workflow makes reference to "Upgrading the SnapCenter Server" when only protecting VMs/Datastores.  However, the SnapCenter Server is no longer required when using SCV to only protect VMs & datastores.  This path should be referring to using the ISO file to upgrade the SCV virtual appliance.  

![Upgrade Workflow Diagram - v4 4](https://user-images.githubusercontent.com/65363075/98205917-37affa80-1ef6-11eb-8064-5a660a93bc8e.jpg)

**Comment by Ronya-Robinson** [comment]
We do have plans to update the SCV 4.2 doc set. The upgrade workflow diagram shown above is not included in the SCV 4.3 and later doc set and has been replaced by a table in the Release Notes of the supported upgrade and migration paths.
