### ISSUE TITLE
Unclear what vCenter permission are needed

### ISSUE THREAD

**Issue by egk4** [NetAppDocs/sc-plugin-vmware-vsphere#22]
Page: [Deployment planning and requirements](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html)

What permissions are needed for the user that is setup and put in the SCV web page that is used to connect the Plug-in to vCenter and used to create snapshot of VM guest?

**Comment by netapp-madhulik** [comment]
Hi,

You can you find more information here:

- [vCenter Server RBAC](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_types_of_rbac_for_snapcenter_users.html#vcenter-server-rbac)
- [Predefined roles packaged with SnapCenter Plug-in for VMware vSphere](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_predefined_roles_packaged_with_snapcenter.html)

Thanks,
Madhulika
