### ISSUE TITLE
inappropriate translation per originator - Text replacement request

### ISSUE THREAD

**Issue by taiganishimura-1129** [NetAppDocs/sc-plugin-vmware-vsphere#23]
Page: [VMware vSphere Web Client Service を再起動します](https://docs.netapp.com/ja-jp/sc-plugin-vmware-vsphere/scpivs44_restart_the_vmware_vsphere_web_client_service.html)

Please replace the text 
「地獄」
under Steps 2 with
「Shell」
(Reverting back to EN text)
Currently, the JP text means "hell" which may make readers uncomfortable and needs immediate replacement.

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @taiganishimura-1129 - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by taiganishimura-1129** [comment]
I noticed this issue has not been solved for a long time even though the issue is critical.
Could you update the text before this ticket expires?

**Comment by ntap-bmegan** [comment]
@taiganishimura-1129 thanks for the update. By commenting, you have prevented the closure. 

@netapp-gudugunti - Please follow up on the inappropriate translation.

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - Do we have an ETA on this?

**Comment by netapp-gudugunti** [comment]
Yes @ntap-bmegan.
ETA is 9/10.

**Comment by ntap-bmegan** [comment]
Is that 10 sep or 9 oct? :)

**Comment by netapp-gudugunti** [comment]
10 Sept.

**Comment by ntap-bmegan** [comment]
We have updated the translation and regenerated the site. 

![image](https://user-images.githubusercontent.com/56453501/188934412-f009181f-f28c-4d06-8915-b263b21b66b8.png)

@taiganishimura-1129 - If you visit the page, the date should show today's date. If it doesn't, you might need to force the page to reload.
