### ISSUE TITLE
SCV 4.4 - Configurations Supported Diagram Needs Updating

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/sc-plugin-vmware-vsphere#3]
![Supported Configurations v 4 4](https://user-images.githubusercontent.com/65363075/98206244-d0467a80-1ef6-11eb-8e82-2a5f1bea7372.jpg)
Page: [Deployment planning and requirements](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html)

The diagram under "Configurations Supported" refers to the Windows SnapCenter Server.  This is no longer valid for use cases where we deploy the SCV appliance as of SCV 4.2 only to do VM/datastore backup/recovery.  This diagram should reference the SCV Appliance instead of the Windows SnapCenter Server.  

We need to distinguish the use case where only SCV is deployed only for VM/datastore backup and vCenter is running in linked or non-linked mode in 2 sites and when SCV is deployed to be used for database backups/recovery when we use the SCV appliance with the Windows SnapCenter Server for the database (i.e. SQL Server) plug-in.

**Comment by Ronya-Robinson** [comment]
The diagram has been updated to show use cases for the SCV appliance.
