### ISSUE TITLE
Changed location for cache

### ISSUE THREAD

**Issue by polarbear-at-home** [NetAppDocs/sc-plugin-vmware-vsphere#30]
Page: [Upgrade to a new patch of the same release of SnapCenter Plug-in for VMware vSphere](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_upgrade_to_a_new_patch.html)

In vCenter 7.0U2 the location for the cached files is different:
/etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/com.netapp.scvm.webclient-4.5.0.6025788

The last part contains the version string of the vsphere-pugin, but the path has changed.

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - Please update status or close if work is complete.
