### ISSUE TITLE
Link on Properties you can override does not work

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/sc-plugin-vmware-vsphere#36]
Page: [Create resource groups](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_resource_groups_for_vms_and_datastores.html)

The link right above item 4 that states "See [Properties you can override]." does not work.  There is no section in the part of the documentation indicating what values can be overridden in the scbr.override file.

The link itself refers to this: https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_resource_groups_for_vms_and_datastores.html#Properties%20you%20can%20override 

![image](https://user-images.githubusercontent.com/65363075/190783466-65ec03fd-0060-4772-9817-89e10c1b4d38.png)

**Comment by netapp-jani** [comment]
The Properties you can override link is fixed in SnapCenter Plug-in for VMware vSphere 4.7. Page: [Create resource groups](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures)
