### ISSUE TITLE
More User Details

### ISSUE THREAD

**Issue by basola55** [NetAppDocs/sc-plugin-vmware-vsphere#38]
Page: [ONTAP privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html)

you can specify which application and which admin leven should be used for the user. Also if the user has to be created in the cluster svm or the data svm.

**Comment by netapp-jani** [comment]
@basola55 

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
The required information is added in SnapCenter Plug-in for VMware vSphere 4.7. Page: [ONTAP privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html#additional-ontap-information)
