### ISSUE TITLE
When using a custom role and user with the Storage Controllers, peer vserver permission is neeeded as well when there is snapmirror replication with the backup

### ISSUE THREAD

**Issue by adiezg** [NetAppDocs/sc-plugin-vmware-vsphere#43]
Page: [ONTAP privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html)

"vserver peer" and probably "vserver peer permission" should be added to the list when using a custom role

**Comment by netapp-jani** [comment]
@adiezg 
Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by adiezg** [comment]
Hello Jani

Thanks for the quick reply.

Best regards

Alfredo Diez

**Comment by netapp-jani** [comment]
@adiezg, After discussing this internally with our engineers, I've updated the page with right information: [ONTAP privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html)

**Comment by adiezg** [comment]
Hello Jani

Many thanks for the changes in the documentation.

Thanks and regards

Alfredo
