### ISSUE TITLE
Required privileges specific to SnapCenter Plug-in for VMware vCenter

### ISSUE THREAD

**Issue by ErikMaier** [NetAppDocs/sc-plugin-vmware-vsphere#45]
Page: [Minimum vCenter privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_vcenter_privileges_required.html)

The privilege names in the docs for version 4.6, 4.7 and 4.8 are not the same as in SCV 4.6, 4.7 and 4.8.

In the doc we have for example: 
netappSCV.Backup.DeleteBackupJob
netappSCV.Backup.BackupNow
netappSCV.Backup.BackupScheduled

and in SCV 4.7 its called:
netappSCV.Backup.DeleteResourceGroup/Backup
netappSCV.Backup.BackupNow
netappSCV.Backup.CreateResourceGroup

We need to update all the privilege names in the docs for SCV 4.6, 4.7 and 4.8.

**Comment by netapp-jani** [comment]
@ErikMaier 
Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@ErikMaier  
Thank you for your feedback. 
Added a table in [SnapCenter Plug-in for VMware vSphere 4.8](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/) page to provide clarity on privileges and labels in UI.
