### ISSUE TITLE
Where's the certs?

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/sc-plugin-vmware-vsphere#46]
Page: [Download the Open Virtual Appliance (OVA)](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_download_the_ova_open_virtual_appliance.html)

Step 5 says to "Browse and select the location of the Entrust Root and Intermediate certificates".  What certs? Where can I find the certs? What does a cert look like?

I can guess and probably figure it out, but I shouldn't have to guess if I'm reading the documentation.

**Comment by netapp-jani** [comment]
@NA-Scott 
Thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@NA-Scott , the [Download the Open Virtual Appliance (OVA)](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_download_the_ova_open_virtual_appliance.html) page is updated with few additional steps. Please review the updated content and let me know if it makes it clear now. Thanks.

**Comment by NA-Scott** [comment]
Yes, much better now. Thank you!

**Comment by netapp-jani** [comment]
Thank you. Closing this issue.
