### ISSUE TITLE
Please review what is supported and unsupported

### ISSUE THREAD

**Issue by pviana13** [NetAppDocs/sc-plugin-vmware-vsphere#48]
Page: [Deployment planning and requirements](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html)

I imagine this is inverted, the page currently says it is NOT supported to "Creating backups with VM consistency".
And IT IS support to "Creating backups without VM consistency".

I think this is wrong. The whole point is to create backups with consistency.

**Comment by netapp-jani** [comment]
@pviana13, thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
We checked on this internally and confirmed that the information we have is correct and so there was no change made to the document. If you have further questions, please send us a note @ doccomments@netapp.com
