### ISSUE TITLE
Link on this page leads nowhere

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/sc-plugin-vmware-vsphere#50]
Page: [Access reports](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_access_reports.html)

In the section on "Last Protection Status of VMs or Datastores Report" there is a link titled [Modify configuration default values](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_modify_configuration_default_values).

That link doesn't lead to anywhere but a 404 error

**Comment by netapp-jani** [comment]
@NA-Scott, thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@NA-Scott The link is now resolved. Please check the page: [Access reports](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_access_reports.html)
Thank you for your feedback.
