### ISSUE TITLE
I know my ABCs

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/sc-plugin-vmware-vsphere#52]
Page: [Minimum vCenter privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_vcenter_privileges_required.html)

Can we get the list on this page alphabetized?

**Comment by netapp-jani** [comment]
@NA-Scott, thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@NA-Scott The Required privileges for vCenter Admin role list is now alphabetized. 
Thank you for your feedback.

Regards,
Jani
