### ISSUE TITLE
NVMe is not supported in SCV

### ISSUE THREAD

**Issue by leahynetapp** [NetAppDocs/sc-plugin-vmware-vsphere#55]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/index.html

### Page title

SnapCenter Plug-in for VMware vSphere documentation

### Summary

This issue was found in case 2009611445
The customer had an issue after implementing NVMe into his environment.  The documentation does not show anywhere if it is supported or not.  Please add segment to warn of this feature not being available or supported.

Currently it is shown as supported in ONTAP docs and SCO.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@leahynetapp, thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@leahynetapp, the Release notes is updated with limitation that NVMe is not supported in SCV 4.9. Thank you again for bringing this to our notice.
