### ISSUE TITLE
Need to update the URL to access the SnapCenter VMware plug-in Swagger web page

### ISSUE THREAD

**Issue by kaminis85** [NetAppDocs/sc-plugin-vmware-vsphere#57]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_access_rest_apis_using_the_swagger_api_web_page.html

### Page title

Access REST APIs using the Swagger API web page

### Summary

When trying to access the URL to access the plug-in Swagger web page:
https://<SCV_IP>:8144/api/swagger-ui/index.html

I was getting HTTP ERROR 404 Not Found.

Instead the below URL was working fine and I was able to access the plugin Swagger web page-
https://<SCV_IP>:8144/api/swagger-ui.html

So, please update the URL wherever it's required.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@kaminis85, thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by kaminis85** [comment]
Got it, thanks for the clarification @netapp-jani. I had tested it with version 4.8, that's why saw this issue.
