### ISSUE TITLE
Release Notes link gets you "400 Bad Request"

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/sc-plugin-vmware-vsphere#58]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_release_notes.html

### Page title

Release notes

### Summary

If you try download the Release Notes, you'll get a 

"Bad Request

Your browser sent a request that this server could not understand."

from here and also from

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/index.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@SPGoetze, we checked the link internally and it seems to be working fine. Please try opening the link again and let us know if you are still seeing the error.

**Comment by netapp-jani** [comment]
@SPGoetze, closing this issue, as the link was refreshed.
