### ISSUE TITLE
Change the description. "If a prescript fails, the backup also fails."

### ISSUE THREAD

**Issue by netapptakayuki** [NetAppDocs/sc-plugin-vmware-vsphere#6]
Page: [Prescripts and postscripts](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_prescripts_and_postscripts.html)

This description is wrong. If the prescript fails, the backup job **complete with warning.** 
![prescript_sentence](https://user-images.githubusercontent.com/78330305/106409187-52f1be00-6483-11eb-969b-416663b0dacb.jpg)

The Evidence image
![prescript_fail](https://user-images.githubusercontent.com/78330305/106408665-2e491680-6482-11eb-9f6d-3b7ba1ecec28.jpg)

The customer think this is very important specification. Would you change this sentence ?

**Comment by Ronya-Robinson** [comment]
I have verified with engineering that you are correct: the backup continues with an error when a prescript fails.
We are working to update the SCV docs as soon as possible.

Thank you for reporting this.
Ronya Robinson
