### ISSUE TITLE
128 TB limit no longer applies.

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/sc-plugin-vmware-vsphere#62]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_resource_groups_for_vms_and_datastores.html

### Page title

Create resource groups

### Summary

The doc says that 128 TB LUNs are supported only on ASA aggregates.

Starting with ONTAP 9.13.0P2 and 9.12.1P2 LUNs and files up to 128TB with volumes up to 300 TB are supported on other controller types too.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@netapp-bingen, thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@netapp-bingen , The page: [Create resource groups](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_resource_groups_for_vms_and_datastores.html) is updated.
