### ISSUE TITLE
Priviledge required

### ISSUE THREAD

**Issue by Jose8RYN** [NetAppDocs/sc-plugin-vmware-vsphere#65]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html

### Page title

ONTAP privileges required

### Summary

Hello Team, 

While helping this customer on a support case he noticed that configuration won't work if the readonly permission for the job show command is not added. 

Is it possible to review and update the doc according to this finding? 

Thanks in advance for your help. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@Jose8RYN, thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@Jose8RYN , our engineer tested backup operation after setting all the privilege values as per the document and it worked fine. If you are still facing issues, please provide more details. You can also write to us @ doccomments@netapp.com to further discuss this issue.
