### ISSUE TITLE
Ontap privileges required

### ISSUE THREAD

**Issue by teotambo** [NetAppDocs/sc-plugin-vmware-vsphere#66]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html

### Page title

ONTAP privileges required

### Summary

With SCV 5 and the use of REST-API full access to job is required otherwise backups won't work.

All-access commands: Minimum privileges required for ONTAP 8.3 and later
...
job 
...

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@teotambo thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@teotambo , our engineer tested backup operation after setting all that privilege values as per the document and it worked fine. If you are still facing issues, please provide more details. You can also write to us @ doccomments@netapp.com to further discuss this issue.

**Comment by netapp-jani** [comment]
@teotambo, please check the page [ONTAP privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html#minimum-ontap-privileges-required). Let us know if this resolves your query.
