### ISSUE TITLE
What is SCV?

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/sc-plugin-vmware-vsphere#69]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html

### Page title

Deployment planning and requirements

### Summary

The section heading uses the term "SCV" and its found 7 times on this particular page, but I have no idea what that acronym stands for. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
The page [Deployment planning and requirements](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html) is updated to show what SCV stands for.
