### ISSUE TITLE
Page is used twice in the sidebar

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/sc-plugin-vmware-vsphere#70]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_download_the_ova_open_virtual_appliance.html

### Page title

Download the Open Virtual Appliance (OVA)

### Summary

I was under "Quick start" but then found myself back in "Get started" because the page is used in both sections of the sidebar.

Also, note that a space is missing in the sidebar before the opening parenthesis.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@netapp-bcammett, this issue is now resolved, please check.

**Comment by netapp-bcammett** [comment]
Looks good. Thank you.
