### ISSUE TITLE
Port required are missing.

### ISSUE THREAD

**Issue by marcj24** [NetAppDocs/sc-plugin-vmware-vsphere#74]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html

### Page title

Deployment planning and requirements

### Summary

In the "Connection and port requirements" it's missing at least 2 port we believe between SCV and the vCenter.
We have seen that port **ICMP** and port **53** is needed for the node.topology.config to be filled we think.

Can you check and update if confirmed ?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@marcj24 
Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
@marcj24 ,

We discussed this internally and observed Node.topology.config is populated using data from vSphere REST API, so there is no need to document additional port information. Hope this helps.

Thanks,
Jani
