### ISSUE TITLE
there are a couple of changes/corrections needed

### ISSUE THREAD

**Issue by dimauro** [NetAppDocs/sc-plugin-vmware-vsphere#75]
### Page URL

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html

### Page title

ONTAP privileges required

### Summary

There is one cluster level command mentioned in the [documentation](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html) and which you can ignore when creating a Role to be associated with a Data Vserver, because you are creating a role based on a Data Vserver, not a cluster. 
that cmddir cannot be associated with a data vserver role, only with a cluster vserver:
security login role create -role scvrole -cmddirname "cluster identity show" -access all
 
Ensure that the below command is run with 'readonly' access instead of 'all', as the current documentation states:
security login role create -role scvrole -cmddirname "vserver" -access readonly -vserver svm1_cluster1
this will avoid getting the error message below:
Error: command failed: A Vserver admin cannot use the specified operation with access level "all". Use a different access level.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@dimauro 
Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Regards,
Jani

**Comment by netapp-jani** [comment]
We have included the request information in the document [ONTAP privileges required](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_minimum_ontap_privileges_required.html#minimum-ontap-privileges-required). Hope this provides more clarity.
