### ISSUE TITLE
Upgrade section not complete

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/sc-plugin-vmware-vsphere#8]
Page: [Upgrade from Windows-based SnapCenter Plug-in for VMware vSphere](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_upgrade_from_windows-based_snapcenter_plug-in_for_vmware_vsphere.html)

First, the above section is migration from 4.1.1 and while it is technically an upgrade, this is commonly called a migration as there is a data transfer process to be done.

Second, there are no steps for how to upgrade from SCV 4.3 or SCV 4.2 to SCV 4.4.  I know the steps are not difficult, but they need to be listed for the customers who don't know.

**Comment by Ronya-Robinson** [comment]
Scott:  Thank you for your input. We will start work on this right away and I will send you a notification when the doc is refreshed.

Ronya
NetApp Information Engineering
